# ==============================
# Options
# ==============================

analytics:
    enabled:    N

# ==============================
# Google Analytics
# ==============================

google:
    id:         UA-X
